[phases.setup]
nixPkgs = ["...", "ffmpeg", "wget"]

[phases.install]
cmds = ["npm install", "wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -O yt-dlp", "chmod +x yt-dlp"]
